[project]
name = "py-receipt-reading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "jinja2>=3.1.6",
    "ollama>=0.6.2",
    "paddleocr>=3.7.0",
    "paddlepaddle>=3.3.1",
    "pillow>=12.3.0",
    "pillow-heif>=1.5.0",
    "pymupdf>=1.28.0",
]
